# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa5af3465d45965bc19541d6676c3f659285543e912234e3c00f45adb14b943c8dfad6e3e6826a1ffe65c378094d80be5d7a3645bb865c504cc7b50dbebeb40d

test:
  secret_key_base: 56c11f4d527bd77606446ef3a7c7f598f01009dcfaa3570345a13a834963798bec415f0d6eb3c7b620711abb43140b6d23b160256c33b18687ee64464a8b9dd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
